export const styles = {
  container: {
    padding: "24px",
  },
  title: {
    fontSize: "24px",
    fontWeight: "bold",
    color: "#1f2937",
    marginBottom: "32px",
  },
  settingsGrid: {
    display: "grid",
    gridTemplateColumns: "1fr",
    gap: "24px",
  },
  section: {
    backgroundColor: "white",
    borderRadius: "12px",
    padding: "24px",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
  },
  sectionHeader: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    marginBottom: "24px",
  },
  sectionIcon: {
    width: "24px",
    height: "24px",
    color: "#4d7051",
  },
  sectionTitle: {
    fontSize: "18px",
    fontWeight: "600",
    color: "#1f2937",
  },
  settingsList: {
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  },
  settingItem: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "12px 0",
  },
  settingInfo: {
    flex: 1,
    marginRight: "24px",
  },
  settingName: {
    fontSize: "16px",
    fontWeight: "500",
    color: "#1f2937",
    marginBottom: "4px",
  },
  settingDescription: {
    fontSize: "14px",
    color: "#6b7280",
  },
  toggle: (active) => ({
    width: "44px",
    height: "20px",
    backgroundColor: active ? "#7ec987" : "#d1d5db",
    borderRadius: "12px",
    padding: "2px",
    cursor: "pointer",
    transition: "background-color 0.2s",
  }),
  toggleHandle: (active) => ({
    width: "20px",
    height: "20px",
    backgroundColor: "white",
    borderRadius: "50%",
    transform: active ? "translateX(23px)" : "translateX(0)",
    transition: "transform 0.2s",
  }),
  wideInput: {
    padding: "10px 16px",
    borderRadius: "6px",
    border: "1px solid #d1d5db",
    backgroundColor: "white",
    fontSize: "14px",
    color: "#1f2937",
    width: "100%",
  },
  profileUploadContainer: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
  },
  profilePicture: {
    width: "80px",
    height: "80px",
    borderRadius: "50%",
    backgroundColor: "#e5e7eb",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  changePhotoButton: {
    padding: "10px 16px",
    borderRadius: "6px",
    border: "none",
    backgroundColor: "#4caf50",
    color: "white",
    fontSize: "14px",
    cursor: "pointer",
    transition: "background 0.2s",
    "&:hover": {
      backgroundColor: "#1d4ed8",
    },
  },
  personalizationContainer: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "20px",
    borderRadius: "8px",
    marginTop: "24px",
  },
  personalizationText: {
    fontSize: "16px",
    fontWeight: "500",
    color: "white",
  },
  personalizeButton: {
    padding: "8px 16px",
    borderRadius: "6px",
    border: "none",
    backgroundColor: "#ffffff",
    color: "#1f2937",
    fontSize: "14px",
    cursor: "pointer",
  },
  saveButtonContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    marginTop: "32px",
    position: "relative",
  },
  saveButton: {
    backgroundColor: "#cce8cf",
    color: "black",
    border: "none",
    padding: "12px 24px",
    borderRadius: "8px",
    fontSize: "16px",
    fontWeight: "bold",
    cursor: "pointer",
    transition: "background-color 0.2s",
    width: "100%",
    maxWidth: "300px",
    boxShadow: "0 2px 4px rgba(0, 0, 0, 0.1)",
  },
  successMessage: {
    backgroundColor: "#e6f7e6",
    color: "#2e7d32",
    padding: "10px 16px",
    borderRadius: "6px",
    marginBottom: "16px",
    fontSize: "14px",
    fontWeight: "500",
    border: "1px solid #b8e6b8",
    width: "100%",
    maxWidth: "300px",
    textAlign: "center",
  },
  // New styles for profile container
  profileContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  },
  profilePhotoSection: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
    marginBottom: "16px",
  },
  profileInputsGrid: {
    display: "grid",
    gridTemplateColumns: "1fr",
    gap: "16px",
    width: "100%",
  },
  inputLabel: {
    display: "block",
    marginBottom: "8px",
    fontSize: "14px",
    fontWeight: 500,
  },
  accountManagementList: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  accountOption: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "12px 16px",
    borderRadius: "8px",
    backgroundColor: "#f3f4f6",
    cursor: "pointer",
    transition: "background-color 0.2s",
    "&:hover": {
      backgroundColor: "#e5e7eb",
    },
  },
  dangerOption: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "12px 16px",
    borderRadius: "8px",
    backgroundColor: "#fee2e2",
    cursor: "pointer",
    transition: "background-color 0.2s",
    "&:hover": {
      backgroundColor: "#fecaca",
    },
  },
  optionIconContainer: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  optionText: {
    fontWeight: 500,
    color: "#1f2937",
    margin: 0,
  },
  optionDescription: {
    fontSize: "14px",
    color: "#6b7280",
    margin: "4px 0 0 0",
  },
  dangerText: {
    fontWeight: 500,
    color: "#ef4444",
    margin: 0,
  },
  dangerDescription: {
    fontSize: "14px",
    color: "#ef4444",
    margin: "4px 0 0 0",
  },
  // Modal styles
  modalOverlay: {
    display: "flex",
    position: "fixed",
    inset: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 50,
  },
  modalHidden: {
    display: "none",
  },
  modalContainer: {
    backgroundColor: "white",
    borderRadius: "8px",
    padding: "24px",
    width: "100%",
    maxWidth: "500px",
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
  },
  modalHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "16px",
  },
  modalTitle: {
    fontSize: "20px",
    fontWeight: 600,
    color: "#1f2937",
    margin: 0,
  },
  closeButton: {
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: "4px",
    borderRadius: "4px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    "&:hover": {
      backgroundColor: "#f3f4f6",
    },
  },
  modalForm: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
  },
  errorMessage: {
    color: "#ef4444",
    fontSize: "14px",
    margin: "4px 0 0 0",
  },
  modalFooter: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "12px",
    marginTop: "16px",
  },
  cancelButton: {
    padding: "8px 16px",
    borderRadius: "6px",
    border: "1px solid #d1d5db",
    backgroundColor: "white",
    color: "#1f2937",
    fontSize: "14px",
    cursor: "pointer",
    transition: "background-color 0.2s",
    "&:hover": {
      backgroundColor: "#f3f4f6",
    },
  },
  submitButton: {
    padding: "8px 16px",
    borderRadius: "6px",
    border: "none",
    backgroundColor: "#7ec987",
    color: "white",
    fontSize: "14px",
    fontWeight: 500,
    cursor: "pointer",
    transition: "background-color 0.2s",
    "&:hover": {
      backgroundColor: "#6bbd76",
    },
  },
  loadingContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "100vh",
  },
  // Additional styles for delete account modal
  deleteModalTitle: {
    fontSize: "20px",
    fontWeight: 600,
    color: "#ef4444",
    margin: 0,
  },
  deleteModalText: {
    fontSize: "16px",
    marginBottom: "12px",
    color: "#1f2937",
  },
  deleteModalSubtext: {
    fontSize: "14px",
    color: "#6b7280",
    margin: "8px 0",
  },
  deleteModalList: {
    fontSize: "14px",
    color: "#6b7280",
    marginLeft: "20px",
    marginTop: "8px",
  },
  deleteButton: {
    padding: "8px 16px",
    borderRadius: "6px",
    border: "none",
    backgroundColor: "#ef4444",
    color: "white",
    fontSize: "14px",
    fontWeight: 500,
    cursor: "pointer",
    transition: "background-color 0.2s",
    "&:hover": {
      backgroundColor: "#dc2626",
    },
  },
};
